### ISSUE TITLE
what is the seed nodes when sync hive chain from block 0

### ISSUE THREAD

**Issue by past2017** [openhive-network/hive#12]
what is the seed nodes when sync hive chain from block 0

**Comment by Gandalf-the-Grey** [comment]
Since vast majority of witnesses and devs who were running seed nodes for Steem, moved with their services to Hive, you can safely use same seed nodes ( for example gtg.steem.house:2001 ). At the time of fork your sync will follow the Hive route, dropping transactions from obsolete fork.

**Comment by past2017** [comment]
> Since vast majority of witnesses and devs who were running seed nodes for Steem, moved with their services to Hive, you can safely use same seed nodes ( for example gtg.steem.house:2001 ). At the time of fork your sync will follow the Hive route, dropping transactions from obsolete fork.

got it , thank you
