### ISSUE TITLE
Missing required owner authority bug on aged (Steemit/D.Tube) migrated accounts

### ISSUE THREAD

**Issue by bakus522** [openhive-network/hive#19]
![image](https://user-images.githubusercontent.com/8198627/81387857-6420c080-90e5-11ea-99d0-f3715ffcd71a.png)

I am unable to access/modify any of my keys. I believe it may have to do with the age and origin of my account, coming from early Steemit and D.Tube. I have my private posting key from the Steemit side, but no active, nor any other key. Possible nulls in my account? @spagetmen is me

Hope I'm contributing correctly!

**Comment by Gandalf-the-Grey** [comment]
You need Private Owner Key or Master Password to perform that operation.
