### ISSUE TITLE
Consider Vote Dilution and Vote Expiration for a future Hard Fork.

### ISSUE THREAD

**Issue by fernandosoder** [openhive-network/hive#20]
Something that always bothered me was the fact that Hive has more equal votes a user can cast than spots in the Security Council(Top 20 witnesses), and also the fact people who are long gone(gave up the Blockchain for some reason) still have influence in governance. So I Thought in a couple suggestions to be discussed.

<h3>Vote Dilution</h3>

* The idea is to divide the value of a witness vote by the amount of voted witnesses.</em>
	* If you have <code>20 HP</code> and vote for one witness, it's a <code>20 HP</code> for it.
	* If you vote for 5 witnesses, it's a <code>4 HP</code> vote for each.
	* If you vote for 20 witnesses, each gets a <code>1 HP</code> vote.
* With such mechanism in place, a takeover attempt would be <em><q>as hard as accumulating 20 times more HP than the whole Hive community</q></em>.
* The more witnesses you vote, less value your vote has to each of them.
* The 30 witnesses limit could be increased to, maybe, 100.

<hr/>
<h3>Vote Expiration</h3>

 * The idea is to make votes for witnesses expire after a while to prevent dead accounts from influencing </em><strong>Hive Governance</strong><em><strong>.</strong></em>
	* <strong>Votes are automatically uncasted after a year.</strong>
		* <em>Can be 6 months, 54 weeks, whatever time developers think is more adequate.</em>
	* <strong>Votes can be renewed before expiration</strong>, *resetting the expiration clock*.
		* <em>Vote renewal before expiration shows the user is still active.</em>
	* <strong>Proxy setup does not expire.</strong>
		* <em>Good for cold storages.</em>
		* <em><strong>But</strong> every proxy-chain must have an active user at the end of it, because his votes will still expire when not renewed.</em>

Expiration for witness votes is a countermeasure against the influence of dead accounts or dead proxy-chains. Only active votes expire, so cold-wallets can still be maintained through proxies or proxy-chains where there must be an active account at the end of each proxy-chain to renew witness votes.

Failure to renew witness votes in an indication that the owner of such account might have lost its keys or abandoned the account for some reason.

---

I am sorry if this topic has already been discussed, but I still believe those suggestions should be considered.

Thank you all for your attention.

**Comment by krischik** [comment]
Sounds like a good idea to me.

**Comment by Gandalf-the-Grey** [comment]
Governance Vote Expiration introduced in HF25
