### ISSUE TITLE
[Enhancement] Required changes to generate a Tax-Report

### ISSUE THREAD

**Issue by marvin-we** [openhive-network/hive#29]
Hello together,

first things first: Thank you all for doing this! I stopped participating in steem and the development of [SteemJ](https://github.com/marvin-we/steem-java-api-wrapper) in 2018 as generating a tax report for myself was a very tough fight. While fighting my way through the things, I've done some notes and created [#2867](https://github.com/steemit/steem/issues/2867) based on that ( [#3116](https://github.com/steemit/steem/issues/3116) seems to be connected too).

The main things are, that:

- all operations that change one of the balances (Savings, HP, HBD, ...) needs to be returned when Operations are queried.
- the factor between vests and hive (m_vests_per_hive?) needs to be accessible for each operation / block (I don't know exactly when it changes).

Would be very nice if this could be improved.

Thank you once again and best regards!

**Comment by Gandalf-the-Grey** [comment]
I think all the features are now in the balance tracker (HAF app)
