### ISSUE TITLE
[Enhancement] Syntax highlight for code blocks

### ISSUE THREAD

**Issue by Jzarecta** [openhive-network/hive#36]
It would be a good feature to have a colored code for markup view. There are many plugins including the different special tags for different language of code.
https://www.markdownguide.org/extended-syntax/#syntax-highlighting

Implementations on different platforms including javascript. https://highlightjs.org/ https://prismjs.com and others.

**Comment by Gandalf-the-Grey** [comment]
That's fronted related, which means it should go to whatever fronend you are using
https://hive.blog - condenser
https://ecency.com - vision
etc.
