### ISSUE TITLE
Blacklisted by accident- Devs please help

### ISSUE THREAD

**Issue by Lichtblick33** [openhive-network/hive#4]
I have voted for @pharesim as my proxy and now I am blacklisted on hive.
I have reported the issue already to @smooth and @therealwolf.
Devs plese help a loyal longterm Steemian. 
<img width="852" alt="Bildschirmfoto 2020-03-20 um 10 00 23" src="https://user-images.githubusercontent.com/62425029/77159917-99763e00-6aa6-11ea-906f-4e8b7c2e9dcc.png">
<img width="710" alt="Bildschirmfoto 2020-03-20 um 11 55 28" src="https://user-images.githubusercontent.com/62425029/77159945-a5620000-6aa6-11ea-95d5-7c5001a044e4.png">

**Comment by pharesim** [comment]
I saw that tonight, but unfortunately the list was discussed too late to fix that mistake. I will delegate 48k HIVE to you until you get your airdrop.

**Comment by krischik** [comment]
I don't think this list was a good idea. Blocking the sock puppet accounts, ok. But for everybody on the else on there was and still is good change of false positives.

**Comment by mahdiyari** [comment]
There are plans to airdrop to users who got into the list by "mistake". Don't panic.

**Comment by pharesim** [comment]
> I don't think this list was a good idea. Blocking the sock puppet accounts, ok. But for everybody on the else on there was and still is good change of false positives.

Not really. People who voted for sockpuppets first but switched to a community proxy during the "voting wars" were mistakenly not excluded from the list. That's just a few, all the rest had their votes changed after the announcement post or not at all, which was the criteria.

**Comment by Lichtblick33** [comment]
Oh that is very kind and much appreciated. I had been in panic mode and now I feel much better.
I am so glad to be on hive board.
Thank you very much for your support and help.
