### ISSUE TITLE
Remove blacklist

### ISSUE THREAD

**Issue by skzap** [openhive-network/hive#5]
I see your blacklist, I think it's an horrible thing to do. Many from the community are supporting my stance, yet they have been censored by the witnesses stake.

Removing the ninja-mined stake is one thing, going over the top and banning people who voted for their witnesses is another. Crypto-currency is all about trust, and hive is starting with 0 trust.

Shame on all the developers included in this hack. @drov0 @roelandp @netuoso 
Your CV will be tainted forever.

This is your last chance to cancel this move

**Comment by ShmoogleOsukami** [comment]
The blacklist in my opinion seems pointless to have if the accounts don't have any stake due to being cut out of the airdrop. 
So yeah in my opinion the blacklist can be removed as it serves no purpose anymore.

**Comment by krischik** [comment]
I'll agree on that the blacklist is a bad idea and sets a bad precedence.

As for the ninja-mined stake: Who is going to delegate the 15 SP every new account needs to functioning. Burning that might turn out to be a mistake as well.3

**Comment by ShmoogleOsukami** [comment]
> I'll agree on that the blacklist is a bad idea and sets a bad precedence.
> 
> As for the ninja-mined stake: Who is going to delegate the 15 SP every new account needs to functioning. Burning that might turn out to be a mistake as well.3

With regard to delegation for new accounts, That is up to the person giving out the account creation tokens. For instance if you provide a signup service it should be in your best interest to hold a decent amount of SP or in the case now HP to delegate to your new signups.

**Comment by krischik** [comment]
> cut out of the airdrop

And that too might be a mistake. We have at least one positive on the list.

Remember Blackstone's ratio: _“It is better that ten guilty persons escape than that one innocent suffer.”_

> Blacklisting them temporarily

A temporarily blacklist would have been better. But no airdrop is pretty final.

**Comment by krischik** [comment]
> That is up to the person giving out the account creation tokens. 

SteemIt did that in the past for most account using the ninja-mined stake. If we destroy the ninja stake who will keep those hundred thousands of plankton accounts afloat?

Those users might not have used Steem for a while, see the news, log in to their old account and have an 0SP unusable account.

**Comment by IntinteDAO** [comment]
@krischik 

>  If we destroy the ninja stake

You CAN'T remove the Ninja Stake, because you'd have to blacklist a lot of whales who support Hive like Blocktrades.

**Comment by ShmoogleOsukami** [comment]
> > That is up to the person giving out the account creation tokens.
> 
> SteemIt did that in the past for most account using the ninja-mined stake. If we destroy the ninja stake who will keep those hundred thousands of plankton accounts afloat?
> 
> Those users might not have used Steem for a while, see the news, log in to their old account and have an 0SP unusable account.

One option is to give an automatic 20sp to new accounts for 3 weeks or so out of thin air that is specifically designed to not effect payouts, witness votes etc, and really only provides RC. Downside is it opens up hive to bot spam attacks possibly. The whole onboarding process and account system probably needs a good review to find out what can be improved.

**Comment by krischik** [comment]
> One option is to give an automatic 20sp to new accounts for 3 weeks or so out of thin air that is specifically designed to not effect payouts, witness votes etc, and really only provides RC.

That's far more complicated than just delegating 20SP.

And more importantly: Most users need far more than 3 weeks to create their first 20SP for their account to be self sufficient.

**Comment by oriolpont** [comment]
> Removing the ninja-mined stake is one thing, going over the top and banning people who voted for their witnesses is another.

@skzap I'm afraid you're misunderstanding the entire point behind Hive. This has little to do with ninja-mined stakes (that is a narrative for Steem, if anything): This is about launching a new coin that explicitly excludes Justin Sun and everything up to his outer spheres of influence, incidental or accidental. This is why the blacklist includes not only accounts reasonably believed to be associated with Steemit, but also his associated witnesses and people who voted them (be it directly or by proxy).

Anyway, that has little to do with Steem, and their funds will remain on the Steem side. Any "crypto-currency" founder has that liberty to decide what is the initial distribution.

Now, is that genius? Is that stupid? Well, we'll see, markets, users, will tell.

**Comment by krischik** [comment]
Back to the actual topic at hand: I now know two accounts which are on the blacklist and should not be there:
 
- [@lichtblick](https://staging.busy.org/@lichtblick) : https://staging.busy.org/@lichtblick/i-am-on-the-hive-blacklist-i-voted-pharesim-as-my-proxy
- [@scottcbusiness](https://staging.busy.org/@scottcbusiness) : https://staging.busy.org/@scottcbusiness/airdrop-hive-sps-proposal

This blacklist was a dumb idea. To get some petty revenge you punished innocent users and destroyed their token. Something you can't reverse.

**This isn't a good start.** — I'm very disappointed.
