### ISSUE TITLE
Sharing transactions between HIVE and STEEM

### ISSUE THREAD

**Issue by skzap** [openhive-network/hive#7]
If Hive is a fork of STEEM, with only the token symbols being different. What prevents me from taking any transaction broadcasted on STEEM, and re-broadcasting it to hive? Not that I do not need the private key to do that, your transaction will already be signed on STEEM.

Obviously this won't work for transfer operations because the symbol changed, but it will work for witness votes, contents, content votes, and so on.

Is this thought of or are you complete idiots?

**Comment by ShmoogleOsukami** [comment]
While this might work or be doable at the start there is a good chance the chains are going to diverge substantially and at that point this kind of functionality will cease to work. So there is little incentive to put development time into such a feature in my opinion.

**Comment by Smittyvb** [comment]
Hive has a different chain ID, and the TaPoS buffers are reset after the fork, preventing such an attack. This would not work.

https://github.com/openhive-network/hive/blob/bc73e54578846fa24f68a768ae1d8ebbb82ee205/libraries/chain/database.cpp#L5551-L5559

**Comment by inertia186** [comment]
> Obviously this won't work for transfer operations because the symbol changed ...

No, I suspect it *will* work for transfers because they are serialized *without* the symbol using the NAI that matches on both networks.

**Comment by crokkon** [comment]
isn't ref_block_num / ref_block_prefix part of the signed part? As soon as the blocks between both chains diverge, the same signed transaction should only be accepted by the one with the matching previous block hash.

**Comment by krischik** [comment]
> using the NAI that matches on both networks.

I too noticed that the NAI's haven't changed.

> Hive has a different chain ID

I was checking the chain ID while upgrading my [Steem Ruby Tutorial](https://github.com/krischik/SteemRubyTutorial) for Hive and noticed with surprise that the chain id and address prefix are still

```ruby
    NETWORKS_HIVE_CHAIN_ID = '0000000000000000000000000000000000000000000000000000000000000000'
    NETWORKS_HIVE_ADDRESS_PREFIX = 'STM'
    NETWORKS_HIVE_CORE_ASSET = ["0", 3, "@@000000021"] # HIVE
    NETWORKS_HIVE_DEBT_ASSET = ["0", 3, "@@000000013"] # HBD
    NETWORKS_HIVE_VEST_ASSET = ["0", 6, "@@000000037"] # VESTS
    NETWORKS_HIVE_DEFAULT_NODE = 'https://api.openhive.network' # √
```

looks very compatible to me. All but the node is the same.

**Comment by quetzalcoatl** [comment]
Then, the case is still open. Anybody feeling brave to try out copying a transaction? If not, I could try in 12-20 hrs

**Comment by prcolaco** [comment]
I was also checking this, as it is a very important issue if not addressed properly. In fact HIVE has the same `CHAIN_ID` and `NAI`'s as STEEM, but it was needed to fork of STEEM as easily as we witnessed. The important thing that prevents the replay attack is TaPoS buffers being reset. In case they were reset, then both chains will become completely isolated as the `ref_block_prefix` will not match on the other chain... Maybe we can double check, but I think that this issue might be closed.

**Comment by Smittyvb** [comment]
Tested it. Got a "transaction tapos exception". Not possible.
