### ISSUE TITLE
Power Up 100% Error

### ISSUE THREAD

**Issue by puncakbukit** [openhive-network/hive#8]
![Screenshot_20200321-131113-698](https://user-images.githubusercontent.com/26822588/77219223-06590900-6b77-11ea-9b5e-b3233cf54406.jpg)

When posting a new article and setting author rewards to "Power Up 100%", result to error "Missing Posting Authority".

**Comment by Gandalf-the-Grey** [comment]
Not related to `hived` itself. I haven't seen recently any other reports of this kind. If you are still experiencing it please feel free to re-open this issue (I will try to pass it to relevant project).
