### ISSUE TITLE
What is the chain id of Hive?

### ISSUE THREAD

**Issue by krischik** [openhive-network/hive#9]
A simple question but the [Hive Developer documentation](https://developers.hive.io/) is currently only a copy of the Steem Developer documentation and simple informations like the chain id is still missing.

# Update

Could it be that the chain id and chain prefix wasn't  changed? 😞

[libraries/protocol/include/steem/protocol/config.hpp](https://github.com/openhive-network/hive/blob/bc73e54578846fa24f68a768ae1d8ebbb82ee205/libraries/protocol/include/steem/protocol/config.hpp):
```cpp
#define STEEM_INIT_PUBLIC_KEY_STR             "STM8GC13uCZbP44HzMLV6zPZGwVQ8Nt4Kji8PapsPiNq1BK153XTX"
#define STEEM_CHAIN_ID fc::sha256()
#define STEEM_ADDRESS_PREFIX                  "STM"
```

**Comment by crokkon** [comment]
`"HIVE_CHAIN_ID":"0000000000000000000000000000000000000000000000000000000000000000"`
`"HIVE_ADDRESS_PREFIX":"STM"`
retrieved from

`curl -s --data '{"jsonrpc":"2.0", "method":"condenser_api.get_config", "params":[], "id":1}' https://api.hive.blog`

**Comment by krischik** [comment]
@crokkon Thanks. That's very helpful.

So the the CHAIN_ID hasn't changed. With all the advantages and disadvantages that brings.

**Comment by Gandalf-the-Grey** [comment]
Finally, after the Eclipse: 
`#define HIVE_CHAIN_ID                         fc::sha256("beeab0de00000000000000000000000000000000000000000000000000000000")`
